FROM phpdockerio/php:8.5-fpm
WORKDIR "/application"

# Install Python and venv
RUN sed -i 's|http://archive.ubuntu.com/ubuntu/|http://mirror.eu.oneandone.net/ubuntu/|g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y php8.5-pgsql \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*
    
COPY Entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
CMD ["php-fpm8.5"]
