###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
#version: '3.1'
services:
    webserver:
        container_name: zet-gtfs-webserver
        restart: unless-stopped
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/nginx/nginx.conf.prod:/etc/nginx/conf.d/default.conf'
            - './var/logs/nginx:/var/log/nginx'
        ports:
            - '20000:80'

    php-fpm:
        container_name: zet-gtfs-php-fpm
        restart: unless-stopped
        build: phpdocker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
            - './var/logs/php-fpm:/var/log'
    
    php-fetcher:
        container_name: zet-gtfs-php-fetcher
        restart: unless-stopped
        build: phpdocker/php-fetcher
        working_dir: /application
        volumes:
            - '.:/application'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
            - './var/logs/php-fpm:/var/log'
        user: www-data
        command: ["php", "/application/scripts/gtfs/fetch_loop.php"]
