status:
    path: /api/status
    controller: App\Controller\StatusController::status
    method: GET
    description: Check if application is online
    requestDto: null
    status_code: 200

info:
    path: /api/info
    controller: App\Controller\StatusController::info
    method: GET
    description: Get application information dump
    requestDto: null
    status_code: 200

get_all_data:
    path: /api/get_data
    controller: App\Controller\DataController::getAllData
    method: GET
    description: Get all data from the GTFS-RT endpoint
    requestDto: null
    status_code: 200

get_vehicles:
    path: /api/vehicles/{route_id}
    controller: App\Controller\VehicleController::getVehicles
    method: GET
    description: Get all vehicles for a specific route
    requestDto: null
    status_code: 200

route_geography:
    path: /api/route/{routeId}/geography
    controller: App\Controller\RouteGeographyController::getRouteGeography
    method: GET
    description: Get route geography for a specific route
    requestDto: null
    status_code: 200
