name: CI

on: push

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest commit

    - name: Set up Docker Compose
      run: docker compose up -d --build

    - name: Install Composer dependencies (php-api)
      run: docker exec zet-gtfs-php-api composer install --no-interaction

    - name: Install Composer dependencies (php-fetcher)
      run: docker exec zet-gtfs-php-fetcher composer install --no-interaction

    - name: Run PHPStan (php-api)
      run: docker exec zet-gtfs-php-api vendor/phpstan/phpstan/phpstan

    - name: Run PHPStan (php-fetcher)
      run: docker exec zet-gtfs-php-fetcher vendor/phpstan/phpstan/phpstan

    - name: Run PHP-CS-Fixer (php-api)
      run: docker exec zet-gtfs-php-api vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --allow-risky=yes --verbose --show-progress dots

    - name: Run PHP-CS-Fixer (php-fetcher)
      run: docker exec zet-gtfs-php-fetcher vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --allow-risky=yes --verbose --show-progress dots